name: clean_arc_flutter
description: Clean Architecture Uptodate

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sn_progress_dialog: ^1.0.2
  timeago: ^3.1.0
  event_bus: ^2.0.0
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  shared_preferences: ^2.0.6
  flutter_modular: ^4.0.1
  dio_http_cache: ^0.3.0
  firstapp:
    git:
      url: https://github.com/muflihmajid/firstappflutter
  dio: ^4.0.0
  connectivity: ^3.0.6
  permission_handler: ^8.1.4+2
  injector: ^2.0.0
  path_provider: ^2.0.2
  logging: ^1.0.1
  flutter_clean_architecture: ^5.0.0
  flutter_dotenv: ^5.0.0
  cupertino_icons: ^1.0.3
  encrypt: ^5.0.0
  intl: ^0.17.0
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - lib/app/ui/assets/images/
   - lib/app/ui/assets/icons/
   - .env